language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: required
install:
- pip install pip==9.0.3
- pip install pytest pytest-cov
- pip install yapf==0.20.0
- pip install coveralls
- python setup.py install
script:
- pytest --cov-config .coveragerc --cov=datmo
- echo $TRAVIS_COMMIT_RANGE
- bash devtools/travis-ci/test_format_code_simple.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
env:
  - LOGGING_LEVEL=DEBUG